export const SHOW_LOADER_AUTH = 'SHOW_LOADER_AUTH';
export const HIDE_LOADER_AUTH = 'HIDE_LOADER_AUTH';

export const LOGIN_REQUEST_START = 'LOGIN_REQUEST_START';
export const LOGIN_REQUEST_SUCCESS = 'LOGIN_REQUEST_SUCCESS';

export const LOGOUT_REQUEST_START = 'LOGOUT_REQUEST_START';
export const LOGOUT_REQUEST_SUCCESS = 'LOGOUT_REQUEST_SUCCESS';

export const LOGIN_GOOGLE_START = 'LOGIN_GOOGLE_START';
export const LOGIN_GOOGLE_SUCCESS = 'LOGIN_GOOGLE_SUCCESS';

export const FORGOT_PASS_REQUEST_START = 'FORGOT_PASS_REQUEST_START';
export const NEW_PASS_REQUEST_SUCCESS = 'NEW_PASS_REQUEST_SUCCESS';
export const VERIFY_CODE_START = 'VERIFY_CODE_START';