export const INITIAL_REQUEST_MAIN_START = 'INITIAL_REQUEST_MAIN_START';
export const INITIAL_REQUEST_MAIN_SUCCESS = 'INITIAL_REQUEST_MAIN_SUCCESS';

export const REQUEST_MAIN_START = 'REQUEST_MAIN_START';
export const REQUEST_MAIN_SUCCESS = 'REQUEST_MAIN_SUCCESS';

export const REGISTER_MAIN_START = 'REGISTER_MAIN_START';
export const REGISTER_MAIN_SUCCESS = 'REGISTER_MAIN_SUCCESS';

export const GET_REQUEST_PRODUCTS_START = 'GET_REQUEST_PRODUCTS_START';
export const GET_REQUEST_PRODUCTS_SUCCESS = 'GET_REQUEST_PRODUCTS_SUCCESS';

export const POST_REQUEST_LINK_START = 'POST_REQUEST_LINK_START';
export const POST_REQUEST_LINK_SUCCESS = 'POST_REQUEST_LINK_SUCCESS';

export const PATCH_REQUEST_PAYMENT_START = 'PATCH_REQUEST_PAYMENT_START';